### ISSUE TITLE
Stack level too deep when upgrading

### ISSUE THREAD

**Issue by andr3w321** [goncalossilva/acts_as_paranoid#104]
Could anyone provide instructions on how to upgrade my code to work with 0.4.0 from 0.2.2?  I was running 0.2.5.  Then I may have soft deleted a couple records (not totally sure, I didn't know this gem was enabled until recently).  When I went to update my Gemfile to 0.4.0 I kept getting

.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14: stack level too deep (SystemStackError)

And rails wouldn't start.  I rolled back to 0.2.5, but it still wasn't working.  I then rolled back one minor version at a time and I can run 0.2.2 just fine, but if I try to upgrade to 0.2.3 I get stack level too deep errors.  Any code upgrade advice would be greatly appreciated as it's a fairly large codebase I'm working with.  Happy to provide more details if needed.

More specifically I'm trying to ultimately fix this code which is supposed to permanently destroy and Incexp object and its dependent objects(installments) permanently.

  # due to acts_as_paranoid weakness, calling incexp.destroy! will permanently remove the incexps, but will mark as deleted the associated installment
  # but we need to permanently remove both of them

def destroy_with_installments_permanently!
  Incexp.transaction do
    installments.each do |i|
      i.destroy!
    end
  # need to reload installments, else the destroy! below will see them as existing and will try do destroy them again
    self.installments(true) 
      self.destroy!
    end
end

Getting the following error:

NoMethodError (undefined method `start_date' for nil:NilClass):
  app/models/audit_observer.rb:166:in`object_description'
  app/models/audit_observer.rb:54:in `after_destroy'
  app/models/incexp.rb:58:in`block (2 levels) in destroy_with_installments_permanently!'
  app/models/incexp.rb:57:in `block in destroy_with_installments_permanently!'
  app/models/incexp.rb:56:in`destroy_with_installments_permanently!'
  app/controllers/ledger_controller.rb:62:in `delete'
  app/controllers/application_controller.rb:148:in`log_audit_events'

I thought a more recent version of the code would have fixed this bug and I could simply call self.destroy! in the method.

**Comment by taelor** [comment]
What version of Rails are you running?

**Comment by andr3w321** [comment]
Rails 3.2.3
I ended up leaving the gem at version 0.2.2 and using the above code which seemed to work.

```
#permanentely delete all installments first
#then destroy incexp permanently outside of this function

 def destroy_with_installments_permanently!
    self.installments.each do |i|
      i.destroy!
    end
 end

@incexp.destroy_with_installments_permanently!
Incexp.only_deleted.where(:id => params[:id]).first.destroy
```

**Comment by taelor** [comment]
hey, just so you know, if you put "```" (three backticks) at the beggining and ending of code blocks, it will format them much nicer for you.

```
class Hello
  puts "world"
end
```

**Comment by andr3w321** [comment]
Thanks, updated.
